name: TypeScript, Vue.js, and CSS Formatting And Linting

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "**.css"
      - "**.ts"
      - "**.vue"

permissions:
  contents: write
  pull-requests: write

jobs:
  format_and_lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.9.0'

    - name: Install dependencies
      run: npm install

    - name: Run Prettier
      run: npm run format

    - name: Run ESLint
      continue-on-error: true
      id: lint
      run: npx eslint src

    - name: Debugging info
      if: success()
      run: |
        git status
      working-directory: ./

    - name: Auto commit Prettier formatted files
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "auto prettier format code"

    - name: Add PR review comment if eslint fails
      if: ${{ steps.lint.outcome == 'failure' }}
      uses: actions/github-script@v4
      with:
        script: |
          const { pull_request } = context.payload;
          const comment = "Your code does not meet our eslint standards.\nPlease run `npm install eslint @eslint/js typescript-eslint eslint-plugin-vue globals && npx eslint src` to lint your code.";
          await github.issues.createComment({
            issue_number: pull_request.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });
          core.setFailed("eslint failed")
