# Inspired by: https://github.com/Comfy-Org/ComfyUI_frontend/blob/57701f6145f622bf17237410c165966fb4aecc75/.github/workflows/test-browser-exp.yaml
name: Update Browser Tests Expectations

# Run on PR merged into master or manually triggered, can assume this always runs on master
# But since master is protected, updated images need to push to a dedicated branch and PR to master
on:
  workflow_dispatch:
  push:
    branches:
      - fix_ci

permissions:
  contents: write
  pull-requests: write

jobs:
  update_browser_expectations:
    runs-on: ubuntu-latest
    steps:
      # Ref: https://github.com/orgs/community/discussions/25199#discussioncomment-3246802
      - name: Get latest ComfyUI release with tag
        id: latestrelease
        run: |
          echo "comfy_latest_release=$(curl -s https://api.github.com/repos/comfyanonymous/ComfyUI/releases/latest | jq '.tag_name' | sed 's/\"//g')" >> $GITHUB_OUTPUT

      - name: Checkout ComfyUI
        uses: actions/checkout@v4
        with:
          repository: comfyanonymous/ComfyUI
          ref: ${{ steps.latestrelease.outputs.comfy_latest_release }}
          path: ComfyUI

      - name: Checkout BizyAir
        uses: actions/checkout@v4
        with:
          repository: siliconflow/BizyAir
          ref: master
          path: ComfyUI/custom_nodes/BizyAir

      - name: Checkout bizyair_frontend
        uses: actions/checkout@v4
        with:
          repository: siliconflow/bizyair_frontend
          path: ComfyUI/custom_nodes/BizyAir/bizyair_frontend

      - name: Create PR
        if: success()
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create --title "Update test expectations" --body "Update test expectations" --base master --head update_snapshots
        working-directory: ComfyUI/custom_nodes/BizyAir/bizyair_frontend