# Inspired by: https://github.com/Comfy-Org/ComfyUI_frontend/blob/57701f6145f622bf17237410c165966fb4aecc75/.github/workflows/test-browser-exp.yaml
name: Update Browser Tests Expectations

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update_browser_expectations:
    runs-on: ubuntu-latest
    steps:
      # Ref: https://github.com/orgs/community/discussions/25199#discussioncomment-3246802
      - name: Get latest ComfyUI release with tag
        id: latestrelease
        run: |
          echo "comfy_latest_release=$(curl -s https://api.github.com/repos/comfyanonymous/ComfyUI/releases/latest | jq '.tag_name' | sed 's/\"//g')" >> $GITHUB_OUTPUT

      - name: Checkout ComfyUI
        uses: actions/checkout@v4
        with:
          repository: comfyanonymous/ComfyUI
          ref: ${{ steps.latestrelease.outputs.comfy_latest_release }}
          path: ComfyUI

      - name: Checkout BizyAir
        uses: actions/checkout@v4
        with:
          repository: siliconflow/BizyAir
          ref: master
          path: ComfyUI/custom_nodes/BizyAir

      - name: Checkout bizyair_frontend
        uses: actions/checkout@v4
        with:
          repository: siliconflow/bizyair_frontend
          path: ComfyUI/custom_nodes/BizyAir/bizyair_frontend

      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: |
            ComfyUI/requirements.txt
            ComfyUI/custom_nodes/BizyAir/requirements.txt

      - uses: actions/setup-node@v4
        with:
          node-version: '20.9.0'
          cache: 'npm'
          cache-dependency-path: |
            ComfyUI/custom_nodes/BizyAir/bizyair_frontend/browser_tests/package-lock.json
            ComfyUI/custom_nodes/BizyAir/bizyair_frontend/package-lock.json

      - name: Install dependencies
        run: |
          pip install -r ComfyUI/requirements.txt
          pip install -r ComfyUI/custom_nodes/BizyAir/requirements.txt
          pip install wait-for-it

      - name: Install playwright
        run: |
          npm install
          npx playwright install chromium --with-deps
        working-directory: ComfyUI/custom_nodes/BizyAir/bizyair_frontend/browser_tests

      - name: Install bizyair_frontend dependencies
        run: |
          npm install
        working-directory: ComfyUI/custom_nodes/BizyAir/bizyair_frontend
              
      - name: Set up test environment
        run: |
          mkdir -p ComfyUI/user/default
          cp -r ComfyUI/custom_nodes/BizyAir/bizyair_frontend/browser_tests/workflows ComfyUI/user/default
      
      - name: Update bizyair_frontend.js
        run: |
          npx vue-tsc -b
          npx vite build
        working-directory: ComfyUI/custom_nodes/BizyAir/bizyair_frontend

      - name: Remove all png from update_snapshots for regen
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch origin update_snapshots
          git checkout -f -b update_snapshots origin/update_snapshots
          git rm -r "**/*.png"
          git commit -m "rm for regen"
          git push
          git checkout ${{ github.ref_name }}
        working-directory: ComfyUI/custom_nodes/BizyAir/bizyair_frontend

      - name: Run Playwright tests and update snapshots
        env:
          BIZYAIR_KEY: ${{ secrets.BIZYAIR_KEY }}
          COMFY_PATH: "../../../.."
        run: |
          rm -r **/*.png
          npx playwright test --update-snapshots --workers=2 --trace on
        working-directory: ComfyUI/custom_nodes/BizyAir/bizyair_frontend/browser_tests

      - uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: playwright-report
          path: ComfyUI/custom_nodes/BizyAir/bizyair_frontend/browser_tests/playwright-report/
          retention-days: 30

      - name: Debugging info
        if: success()
        run: |
          git status
        working-directory: ComfyUI/custom_nodes/BizyAir/bizyair_frontend/browser_tests

      # Using a dedicated branch to update test expectations, because
      # master is protected, updated images need to push to that branch and PR to master
      # NOTE: PR from github action bot is not enabled so need to manually create a PR
      - name: Commit updated expectations
        if: success()
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update test expectations [skip ci]"
          file_pattern: "*.png"
          branch: update_snapshots
          skip_fetch: true
          skip_checkout: false
          repository: ComfyUI/custom_nodes/BizyAir/bizyair_frontend/browser_tests
